name: "CI"

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:

    - name: Environment
      run: |
        env
        
    - uses: actions/checkout@v1
    
    - name: Install Dependencies and get source code
      run: |
        sudo apt-get update
        sudo apt-get -y install imagemagick gcc libncurses5-dev liblua5.3-dev git make zip unzip libjpeg-dev x11-common libpthread-stubs0-dev libxmu-dev mesa-common-dev z80asm libglu1-mesa-dev freeglut3-dev 
        wget https://www.autometer.de/unix4fun/z80pack/ftp/z80pack-1.36.tgz
        tar -xvf z80pack-1.36.tgz
        
    - name: Build
      run: |
        cd z80pack-1.36/
        cd frontpanel/
        make -f Makefile.linux
        sudo cp libfrontpanel.so /usr/lib/x86_64-linux-gnu/
        cd ../cpmsim/srcsim/
        make -f Makefile.linux
        cd ../../altairsim/srcsim/
        make -f Makefile.linux
        cd ..
        ls -lh
        
    - name: Put together AppDir
      run: | 
        mkdir -p ./appdir/usr/bin ./appdir/usr/share/icons/hicolor/256x256/apps ./appdir/usr/share/applications ./appdir/usr/share/altairsim
        cp altairsim.desktop  ./appdir/usr/share/applications/
        cp -r ./z80pack-1.36/altairsim/* ./appdir/usr/bin
        convert 349-3492692_mic-torino-altair8800-8-bit-mikrocomputer-bausatz-mits.png  -resize 256x256 -gravity center -background none -extent 256x256 ./appdir/usr/share/icons/hicolor/256x256/apps/altairsim.png
        rm -rf ./appdir/usr/bin/srcsim # Source is not needed there
        mv ./appdir/usr/bin/conf ./appdir/usr/bin/disks ./appdir/usr/share/altairsim
        find ./appdir
        find ./appdir -type f -exec sed -i -e 's|/usr/local|./././././|g' {} \;
        
    - name: Generate AppImage
      run: |
        APPDIR=$(readlink -f appdir) # Why is this needed?
        wget -c -q https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
        chmod +x appimagetool-*.AppImage
        ./appimagetool-*.AppImage deploy "$APPDIR"/usr/share/applications/*.desktop --appimage-extract-and-run # Bundle EVERYTHING
        ./appimagetool-*.AppImage "$APPDIR" --appimage-extract-and-run # turn AppDir into AppImage

    - name: Release AppImage
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: AppImage
        automatic_release_tag: continuous
        prerelease: true
        draft: false
        files: |
          altairsim*.AppImage*
        repo_token: ${{ secrets.GITHUB_TOKEN }}
